# Generated by Django 2.2.1 on 2019-06-02 09:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IndexBlogShow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.SmallIntegerField(default=0, verbose_name='展示顺序')),
                ('blog_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blogs.Blog', verbose_name='blog推荐')),
            ],
            options={
                'verbose_name': '首页文章推荐',
                'verbose_name_plural': '首页文章推荐',
                'db_table': 'df_index_blog_show',
            },
        ),
    ]
